version: 2
updates:
  - package-ecosystem: "cargo"
    directories: ["/enclaves/**/*"]
    schedule:
      interval: "weekly"
    open-pull-requests-limit: 3
    labels:
      - "dependencies"
      - "rust"