name: SgxSDK

on:
  workflow_dispatch:

jobs:
  push:
    runs-on: ubuntu-24.04
    permissions:
      contents: read  # checkout
      packages: write # Push Docker Image to ghcr.io
    steps:
      - uses: actions/checkout@v4
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ github.token }}
          logout: true
      - id: metadata
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/${{ github.repository }}/intel-sgx-sdk
          tags: |
            type=sha,prefix=,format=long
      - name: Build and Push
        uses: docker/build-push-action@v5
        id: docker_build_and_push
        with:
          context: ./sgxsdk
          push: true
          tags: ${{ steps.metadata.outputs.tags }}
          labels: ${{ steps.metadata.outputs.labels }}
          cache-from: type=registry,ref=ghcr.io/${{ github.repository }}/intel-sgx-sdk:buildCache
          cache-to: type=registry,ref=ghcr.io/${{ github.repository }}/intel-sgx-sdk:buildCache,mode=max
